site_name: Spark JMS Connector
site_url: https://dyaraev.github.io/spark-jms-connector/
repo_url: https://github.com/dyaraev/spark-jms-connector
theme:
  name: material
#  highlightjs: true
  custom_dir: docs/overrides
  palette:
    - scheme: slate
      primary: orange
      accent: yellow
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.integrate
  font:
    text: Roboto
    code: Inconsolata

extra_css:
  - css/extra.css
  - css/fonts.css
#  - css/pygments.css

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Configuration Options: configuration.md
  - Development: development.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.blocks.html
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
#      use_pygments: false
  - toc:
      permalink: true

plugins:
  - search
  - privacy:
      enabled: true
  - mike:
      alias_type: symlink
      canonical_version: latest
      redirect_template: docs/overrides/redirect.html
      version_selector: true

copyright: <p>Copyright &copy; <script>document.write(new Date().getFullYear())</script>. All Rights Reserved.</p>

extra:
  generator: true
  version:
    provider: mike
  commit_hash: !ENV COMMIT_HASH
