name: Build and Release Artifacts

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci.yml
      - .github/workflows/build-for-version.yml
      - common/**
      - connector-v1/**
      - connector-v2/**
      - provider-activemq/**
      - project/**
      - build.sbt
      - scalafix.conf
      - scalafmt.conf
      - version.sbt

  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/ci.yml
      - .github/workflows/build-for-version.yml
      - common/**
      - connector-v1/**
      - connector-v2/**
      - provider-activemq/**
      - project/**
      - build.sbt
      - scalafix.conf
      - scalafmt.conf
      - version.sbt

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  build-spark35:
    uses: ./.github/workflows/build-for-version.yml
    with:
      spark_version: "3.5.7"

  build-spark40:
    uses: ./.github/workflows/build-for-version.yml
    with:
      spark_version: "4.0.1"

  build-spark41:
    uses: ./.github/workflows/build-for-version.yml
    with:
      spark_version: "4.1.0"
