name: Build and Publish

on:
  push:
    branches: [ "master" ]
    tags: [ "**" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'sbt'

    - name: Setup sbt launcher
      uses: sbt/setup-sbt@v1

    - name: Configure workflow
      id: configure
      run: |
        export VERSION=$(sbt "print version" | tail -n 1 | xargs)
        echo "$VERSION"
        echo "version=$VERSION" >> GITHUB_OUTPUT

    - name: Test version correctness
      run: |
        echo "Version is: ${{ steps.configure.outputs.version }}"

#    - name: Run checks
#      if: ${{ github.event_name == 'pull_request' }}
#      run: sbt compile scalafmtCheck "scalafix --check" assembly
#
#    - name: Assemble JARs
#      run: sbt assembly

#    - name: Upload build artifacts
#      uses: actions/upload-artifact@v4
#      with:
#        name: artifacts
#        paths: |
#          - connector-v1/target/scala-2.12/spark-jms-connector-v2-${{ PROJECT_VERSION }}.jar
#          - connector-v2/target/scala-2.12/spark-jms-connector-v2-${{ PROJECT_VERSION }}.jar

#    - name: Publish JARs
#      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
#      env:
#        GH_TOKEN: ${{ secrets.GH_TOKEN }}
#      run: |
#        gh release create v1.2.3 release.tar.xz

    # Optional: This step uploads information to the GitHub dependency graph and unblocking Dependabot alerts for the repository
    # - name: Upload dependency graph
    #   uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
