name: Build and Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - docs/**
      - mkdocs.yml
      - .github/workflows/ci-docs.yml

  pull_request:
    branches:
      - main
    paths-ignore:
      - docs/**
      - mkdocs.yml
      - .github/workflows/ci-docs.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'sbt'

    - name: Setup sbt launcher
      uses: sbt/setup-sbt@v1

    - name: Configure build
      id: configure
      run: |
        VERSION=$(sbt -Dsbt.log.noformat=true "print version" | tail -n 1 | xargs)
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Run checks and build JARs
      run: sbt compile scalafmtCheck "scalafix --check" assembly

    - name: Upload JARs for connector-v1
      uses: actions/upload-artifact@v4
      with:
        name: spark-jms-connector-v1-${{ steps.configure.outputs.version }}.jar
        path: connector-v1/target/scala-2.12/spark-jms-connector-v1-${{ steps.configure.outputs.version }}.jar
        if-no-files-found: error

    - name: Upload JARs for connector-v2
      uses: actions/upload-artifact@v4
      with:
        name: spark-jms-connector-v2-${{ steps.configure.outputs.version }}.jar
        path: connector-v2/target/scala-2.12/spark-jms-connector-v2-${{ steps.configure.outputs.version }}.jar
        if-no-files-found: error

    - name: Upload JARs for provider-activemq
      uses: actions/upload-artifact@v4
      with:
        name: spark-jms-provider-activemq-${{ steps.configure.outputs.version }}.jar
        path: provider-activemq/target/scala-2.12/spark-jms-provider-activemq-${{ steps.configure.outputs.version }}.jar
        if-no-files-found: error

    # Optional: This step uploads information to the GitHub dependency graph and unblocking Dependabot alerts for the repository
    # - name: Upload dependency graph
    #   uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
